// Generated by CoffeeScript 1.6.3
(function() {
  var FacebookButton, FeedlyButton, HatenaBookmark, TweetButton, htmlTag, rMeta, rUrl, util;

  util = require("../../util");

  htmlTag = util.html_tag;

  rUrl = /((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[.\!\/\\w]*))?)/;

  rMeta = /["']?([^"']+)?["']?\s*["']?([^"']+)?["']?/;

  HatenaBookmark = (function() {
    HatenaBookmark.prototype.TYPES = {
      SMALL: "simple",
      LARGE: "standard"
    };

    HatenaBookmark.prototype.DISPLAY_TYPES = {
      VISIBLE: "balloon",
      UNVISIBLE: "noballoon",
      VERTICAL: "vertical-balloon"
    };

    HatenaBookmark.prototype.LANGS = {
      JA: "ja",
      EN: "en"
    };

    function HatenaBookmark(type, display_type, lang) {
      this.type = type;
      this.display_type = display_type;
      this.lang = lang;
      if (!this.type) {
        this.type = this.TYPES.LARGE;
      }
      if (!this.display_type) {
        this.layout = this.DISPLAY_TYPES.VERTICAL;
      }
      if (this.display_type !== this.DISPLAY_TYPES.VERTICAL) {
        this.layout = "" + this.type + "-" + this.display_type;
      }
      if (!this.langs) {
        this.lang = this.LANGS.JA;
      }
    }

    HatenaBookmark.prototype.getHtmlCode = function() {
      return "<a href=\"http://b.hatena.ne.jp/entry/" + this.url + "\" \n   class=\"hatena-bookmark-button\" \n  data-hatena-bookmark-title=\"" + this.title + "\" \n  data-hatena-bookmark-layout=\"" + this.display_type + "\"\n  data-hatena-bookmark-lang=\"" + this.lang + "\"\n  title=\"このエントリーをはてなブックマークに追加\">\n  <img src=\"http://b.st-hatena.com/images/entry-button/button-only@2x.png\"\n       alt=\"このエントリーをはてなブックマークに追加\"\n       width=\"20\"\n       height=\"20\"\n       style=\"border: none;\" />\n</a>\n<script type=\"text/javascript\" \n        src=\"http://b.st-hatena.com/js/bookmark_button.js\" \n        charset=\"utf-8\" \n        async=\"async\"></script>";
    };

    return HatenaBookmark;

  })();

  TweetButton = (function() {
    TweetButton.prototype.TYPES = {
      SHARE: 1,
      FOLLOW: 2,
      HASHTAGS: 3,
      TWEET: 4
    };

    TweetButton.prototype.COUNT_TYPES = {
      NONE: 1,
      HORIZONTAL: 1,
      VERTICAL: 2
    };

    function TweetButton(type, username, recommend_username, hashtag, size, count, lang) {
      this.type = type;
      this.username = username;
      this.recommend_username = recommend_username;
      this.hashtag = hashtag;
      this.size = size;
      this.count = count;
      this.lang = lang;
      if (!this.type) {
        this.type = this.TYPES.SHARE;
      }
      this.lang = 'en';
      if (!this.count) {
        this.count = this.COUNT_TYPES.VERTICAL;
      }
    }

    return TweetButton;

  })();

  FacebookButton = (function() {
    FacebookButton.prototype.LAYOUTS = {
      STANDARD: 1,
      BOX_COUNT: 2,
      BUTTON_COUNT: 3,
      BUTTON: 4
    };

    FacebookButton.prototype.ACTIONS = {
      LIKE: 1,
      RECOMEND: 2
    };

    function FacebookButton(layout, action, is_show_faces) {
      this.layout = layout;
      this.action = action;
      this.is_show_faces = is_show_faces;
      if (!this.layout) {
        this.layout = this.LAYOUTS.BOX_COUNT;
      }
      if (!this.action) {
        this.action = this.ACTIONS.LIKE;
      }
    }

    return FacebookButton;

  })();

  FeedlyButton = (function() {
    FeedlyButton.prototype.BUTTON_TYPES = {
      FLAT_LARGE: 1
    };

    function FeedlyButton(type) {
      this.type = type;
      if (!this.type) {
        this.type = this.BUTTON_TYPES.FLAT_LARGE;
      }
    }

    FeedlyButton.prototype.getHtmlCode = function() {};

    return FeedlyButton;

  })();


  /*
  Social Tag
  
  Syntax:
  {% social %}
   */

  hexo.extend.tag.register('social', function(args, content) {
    var hb;
    hb = new HatenaBookmark;
    return hb.getHtmlCode();
  });

}).call(this);
